steps:
  - id: Login
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  - id: Build
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t $$USERNAME/$_DOCKER_HUB_REPOSITORY:$TAG_NAME \
          -t $$USERNAME/$_DOCKER_HUB_REPOSITORY:latest \
          --cache-from $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME:latest \
          --build-arg BUILD_TAG_NAME=$TAG_NAME \
          --build-arg BUILD_SHORT_SHA=$SHORT_SHA \
          -f docker/Dockerfile \
          .
    secretEnv: ['USERNAME']

  - id: Push1
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/$_DOCKER_HUB_REPOSITORY:$TAG_NAME']
    secretEnv: ['USERNAME']

  - id: Push2
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/$_DOCKER_HUB_REPOSITORY:latest']
    secretEnv: ['USERNAME']

availableSecrets:
  secretManager:
    - versionName: projects/four-spaces/secrets/docker-password/versions/1
      env: 'PASSWORD'
    - versionName: projects/four-spaces/secrets/docker-username/versions/1
      env: 'USERNAME'

options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: europe-docker.pkg.dev
  _AR_REPOSITORY: eu.gcr.io
  _DOCKER_HUB_REPOSITORY: kso-betterstack-integration
timeout: 1200s
